### ISSUE TITLE
Example 13 missing 'text/plain' content object

### ISSUE THREAD

**Issue by richardcarls** [dissolve/jf2#10]
http://dissolve.github.io/jf2/#simplified-json

The plain-text representation of the content in Example 12 is missing in the JF2 of Example 13.

**Comment by dissolve** [comment]
JF2 intentionally does not support multiple copies of the same content in different formats.  The simplification step prefers the more expressive HTML content to the plaintext one.  If plaintext is desired, that can always be parsed later.   Perhaps a note explaining this would be useful.

**Comment by richardcarls** [comment]
I didn't realize that was the case, but it makes sense. A rewording or small addition under 4.4 would be great.
