### ISSUE TITLE
Example 13: author card should be moved to references property

### ISSUE THREAD

**Issue by richardcarls** [dissolve/jf2#11]
http://dissolve.github.io/jf2/#simplified-json

**Comment by dissolve** [comment]
References was intended initially to be optional and it is explained as such in 
http://dissolve.github.io/jf2/#post-properties
http://dissolve.github.io/jf2/#using-references

But not clearly expressed in 
http://dissolve.github.io/jf2/#reservedkeywords

I'm thinking it should probably be strengthened to say MUST use references for any non-authoritative data. and perhaps a few other examples should illustrate this as well

**Comment by richardcarls** [comment]
I agree with strengthening it to require references for these instances, where a uid / url exists that points to the authoritative source.

**Comment by dissolve** [comment]
Due to time constraints at this point and this would potentially force code changes, the group agreed to reject this change https://www.w3.org/wiki/Socialwg/2017-12-19-minutes (once the meeting notes are posted)
