### ISSUE TITLE
consider adopting XRay format for HTML valued properties like 'content'

### ISSUE THREAD

**Issue by tantek** [dissolve/jf2#13]
compare https://github.com/aaronpk/XRay#response-format and https://indieweb.org/jf2#Example

The XRay portion uses 'content' with two keys inside "html" and "text". This seems easier to consume that the way jf2 does it with content-type and value.

cc: @aaronpk

**Comment by dissolve** [comment]
looking at the format in the JF2Feed version, I'm leaning toward this being a useful change.  I don't see what other content types would be really useful besides text and html
@kevinmarks thoughts?

**Comment by aaronpk** [comment]
The problem with the current format is that there isn't a way to include both a plaintext and HTML value. That's one of the benefits of the XRay/mf2 version, so consumers can use the HTML value if they can handle HTML, otherwise can use the plaintext version without any parsing.

**Comment by dissolve** [comment]
This has been done in the latest version.  I think it does make a good amount of sense.
