### ISSUE TITLE
Don't Equate Sex with Gender

### ISSUE THREAD

**Issue by dissolve** [dissolve/jf2#2]
Sex is aliased to vcard:hasGender, this is clearly incorrect
https://github.com/w3c-social/activipy/pull/2

copy of https://github.com/dissolve/socialstream/issues/6

**Comment by dissolve** [comment]
reopen to ensure @gobengo has a chance to review

**Comment by gobengo** [comment]
+1 !!!

**Comment by dissolve** [comment]
I'll take that as its good to close :)
