### ISSUE TITLE
Why is JF2 Feed non-normative?

### ISSUE THREAD

**Issue by strugee** [dissolve/jf2#20]
It doesn't quite sit right with me that the JF2 Feed section is non-normative. I guess I could see an argument that it's just explaining a particular profile that's already doable if you look hard enough at the mf2 spec, but it seems like a pretty important use-case that we should really nail down. It also seems sketchy that we're registering a media type with IANA but the stuff defining what that type actually constitutes is non-normative, but I'm certainly not familiar with the norms here and am happy to be corrected.

Thoughts?

**Comment by dissolve** [comment]
It is normative, only the introduction sections are not

**Comment by strugee** [comment]
Whoops. Misread, sorry

**Comment by dissolve** [comment]
No problem.
I can see why you would think that though.  It is a little confusing the way that it gets formatted.  But that's the way the template is.  Not really under my control.
