### ISSUE TITLE
Why is there an Implementations section?

### ISSUE THREAD

**Issue by strugee** [dissolve/jf2#24]
Having a list of implementations in a spec is highly unusual and I don't see what value this really provides - particularly since most of the descriptions are pretty vague and none of the implementations listed (except Webmention.io) describe the differences between JF2 and their formats.

Seems like this would be much better suited to the W3C wiki?

**Comment by dissolve** [comment]
Before publishing as a final version (Note) I would agree it makes sense to remove it, but as it is still very much a work in progress to standardize between current implementations, I think it makes sense to keep in draft versions to give reference to exactly how others are using it currently

**Comment by strugee** [comment]
Cool, makes sense to me. Feel free to close or keep open as a reminder as you see fit :thumbsup:

**Comment by strugee** [comment]
It'd be nice too if the section showed how much implementations diverge from the spec. Can't remember for sure but I seem to recall @aaronpk saying that Webmention.io had diverged a fair amount?

**Comment by dissolve** [comment]
it has not anymore, his implementations are fully compliant, it does wrap it in an object to describe the actual HTTP response

**Comment by dissolve** [comment]
This section has been removed for move to NOTE anyway
