### ISSUE TITLE
Why is outer context an object and not a list?

### ISSUE THREAD

**Issue by kevinmarks** [dissolve/jf2#3]
If I have multiple items on a page in mf2 json form, how am I supposed to represent this in jf2? Just pick the first one?

**Comment by kevinmarks** [comment]
For example, http://stream.thatmustbe.us/?url=http://aaronpk.com&op=mf2-jf2 creates an outer context with children and no data - is that expected?

my non-children-handling one currently does this:

http://www.unmung.com/mf2tojs2?url=http%3A%2F%2Fwww.unmung.com%2Fmf2%3Furl%3Daaronpk.com%26html%3D%26pretty%3Don&pretty=on

**Comment by dissolve** [comment]
That is expected, @aaronpk and I had discussed several ways to do this.  and this seemed to be the simplest method for it without changing the model to represent the entire document like mf2-json does now (and thus lose some shortness of JF2) 

http://dissolve.github.io/jf2/jf2-core.html#multiple-items
