### ISSUE TITLE
Need to add language about when children is used for multi-valued properties.

### ISSUE THREAD

**Issue by kevinmarks** [dissolve/jf2#4]
Also, should we require non-duplicate multiple properties? I have seen mf2 markup int the wild that ends up with 2 identical urls in an h-card.

**Comment by dissolve** [comment]
It does specify that the children is for unnamed sub-objects.  "unnamed" is clearly the wrong word there.  Would "Children is a container for all sub-objects of an entry that do not fit in to any specific property." make this clearer?

For properties I think that makes sense, duplicate identical properties really doesn't make any sense.

I wonder if it would make sense to make 'url' a reserved word and define that it can only be single value.  If the urls are identical, we can treat that as a single value and leave it to implementor to determine exactly how they want to figure out the single "correct" value.
