### ISSUE TITLE
missing JSON-LD context file

### ISSUE THREAD

**Issue by danbri** [dissolve/jf2#7]
Maybe this should be at https://www.w3.org/ns/js2 somewhere, I'm not sure. 

The JSON-LD Consideration section i.e. http://dissolve.github.io/jf2/#JSON-LD has a 404 to https://github.com/dissolve/jf2/blob/master/jf2-context.jsonld ... is that file being packaged up for W3C publication too?

**Comment by sandhawke** [comment]
I don't exactly understand js2 but I'd expect if there is a jsonld context it should be on w3.org, yeah

**Comment by danbri** [comment]
Oh, I was hoping you did understand it; specifically its relationship to JSON-LD.  The abstract is pretty general: "This document describes a JSON serialization format to describe simple streams of data as well as single objects of data for data transfer and processing.". But there's no W3C law against having several approaches to overlapping problems.

**Comment by dissolve** [comment]
Hey, sorry about that, the context file like was incorrect.  It has been corrected now.

**Comment by danbri** [comment]
Will you publish it at w3.org?

**Comment by dissolve** [comment]
Yes, I would assume it will be.

**Comment by danbri** [comment]
@sandhawke - will you handle that? does it need an issue opening somewhere else?

**Comment by sandhawke** [comment]
I've installed it at http://www.w3.org/ns/jf2

Can you link to it there, instead, @dissolve ?

Right now it's just the json-ld.   Maybe @rhiaro wants to do the magic to make an HTML version for us as well, at some point.

**Comment by danbri** [comment]
Thanks! FWIW we have been having an unfun time trying to content negotiate the same URL (http://schema.org/) as JSON-LD and HTML; caching variants is a pain to get right. https://github.com/schemaorg/schemaorg/issues/1219 ...
