### ISSUE TITLE
References updates

### ISSUE THREAD

**Issue by tantek** [dissolve/jf2#9]
There are a bunch of references updates that are needed.
- JSON-LD, since it is not required, should be an informative (non-normative) reference
- Add references to:
  - microformats2 parsing spec - http://microformats.org/wiki/microformats2-parsing
  - h-entry - http://microformats.org/wiki/h-entry

**Comment by dissolve** [comment]
forgot to make ticket reference in the commit message.  This is updated now.  Please review again.
https://github.com/dissolve/jf2/commit/021f2dbccf6a2dca67dde05211bd605e40ca47d0
